### ISSUE TITLE
[Bug] when use `useSquare==true`, the rendering has a bug in Y axis .

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-tilemap#25]
When the map scroll in Y (the viewport moves down) , 

the tiles in the top line (in viewport) will disappear too early , 
and the bottom line  (in viewport) will disappear too late.

------
But X axis never with wrong.
When the map scroll  in X (the viewport moves right)   ,  everything is OK.

If not use useSquare==true,   everything is also OK.

**Comment by ivanpopelyshev** [comment]
I think to drop that thing in 2.0 version, and use instancing instead.

**Comment by finscn** [comment]
the `vec2 clamped` in square.frag is never be used.  Is it about this bug ?

**Comment by ivanpopelyshev** [comment]
You sure that you need squares and gl.POINT? I just wanted vertex buffer to be 4 times smaller, that's why i used gl.POINT. I started to think about 2.0 yesterday , when you started your crusade in pixi-tilemap, and I'm starting to code it right now.

Can I look at your game pretty please? May be I'll see some other ideas for plugins :)

**Comment by finscn** [comment]
Thank you very much.
But I'm a poor man. In China , if you can't give lots of money or a big house for  mortgage (bad english),  you can't go abroad freely.

So sad ...  tears... 

-----
I'll create a PR soon
